[package]
name = "investments"
version = "2.5.2"
description = "Helps you with managing your investments"
keywords = ["finance", "investment", "stocks", "trading", "taxes"]
categories = ["command-line-utilities"]

authors = ["Dmitry Konishchev <konishchev@gmail.com>"]
homepage = "https://github.com/KonishchevDmitry/investments"
repository = "https://github.com/KonishchevDmitry/investments"
documentation = "https://github.com/KonishchevDmitry/investments"
license = "GPL-3.0+"
readme = "README.md"

edition = "2018"
exclude = ["/testdata"]
default-run = "investments"

[[bin]]
name = "investments"
path = "src/bin/investments/mod.rs"

[[bin]]
name = "tax-statement-parser"
path = "src/bin/tax_statement_parser.rs"

[dependencies]
ansi_term = "0.12.1"
calamine = "0.16.2"
chrono = "0.4.19"
chrono-tz = "0.5.3"
cast = "0.2.3"
clap = "2.33.3"
csv = "1.1.5"
easy-logging = "0.1.1"
encoding_rs = "0.8.26"
governor = "0.3.1"
indoc = "1.0.3"
lazy_static = "1.4.0"
log = "0.4.11"
maplit = "1.0.2"
matches = "0.1.8"
num-traits = "0.2.14"
prettytable-rs = "0.8.0"
prometheus = "0.11.0"
quick-xml = { version = "0.20.0", features = [ "serialize" ] }
rayon = "1.5.0"
regex = "1.4.2"
reqwest = { version = "0.10.10", features = ["blocking", "json"] }
rust_decimal = "1.9.0"
rust_decimal_macros = "1.9.0"
separator = "0.4.1"
serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1.0.61"
serde_yaml = "0.8.14"
serde-xml-rs = "0.4.0"
shellexpand = "2.1.0"

diesel = { version = "1.4.5", features = ["sqlite", "chrono"] }
diesel-derive-enum = { version = "1.1.0", features = ["sqlite"] }
diesel_migrations = "1.4.0"
# The version spec must be in sync with https://github.com/diesel-rs/diesel/blob/master/diesel/Cargo.toml
libsqlite3-sys = { version = ">=0.8.0, <0.19.0", features = ["bundled"] }

static_table_derive = "0.1.15"
xls_table_derive = "0.3.8"

[patch.crates-io]
static_table_derive = { path = "src/formatting/static_table_derive" }
xls_table_derive = { path = "src/xls/xls_table_derive" }

[dev-dependencies]
mockito = "0.28.0"
qtrac-retest = "4.0.6"
rstest = "0.6.4"
tempfile = "3.1.0"
url = "2.2.0"
