[package]
name = "xls_table_derive"
version = "0.3.10"
description = "Procedural macros for investments crate"

authors = ["Dmitry Konishchev <konishchev@gmail.com>"]
homepage = "https://github.com/KonishchevDmitry/investments"
license = "GPL-3.0+"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
darling = "0.12.0"
proc-macro2 = "1.0.24"
quote = "1.0.8"
syn = "1.0.59"
